package vn.ds.study.mi.connector.gcs.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import org.apache.axiom.om.OMElement;
import vn.ds.study.mi.connector.gcs.utils.Error;

@Getter
@AllArgsConstructor
@Builder
public class ListObjectResult {

    private String operation;

    /**
     * Is operation successfully executed
     */
    private boolean isSuccessful = false;

    /**
     * Number of written bytes to file
     */
    private int writtenBytes = 0;

    /**
     * Error code
     */
    private Error error;

    /**
     * Error message
     */
    private String errorMessage;

    /**
     * Optional result element generated by the operation
     */
    private OMElement resultEle;
}
